[tool.poetry]
name = "family-tree-generator"
version = "0.1.0"
description = ""
authors = ["SubhomoyRoy <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
whaaaaat = "^0.5.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
